// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Timeify.Infrastructure.Context.App;

namespace Timeify.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    internal class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Timeify.Core.Entities.RefreshTokenEntity", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasAnnotation("SqlServer:ValueGenerationStrategy",
                        SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<DateTime>("Created");

                b.Property<DateTime>("Expires");

                b.Property<DateTime>("Modified");

                b.Property<string>("RemoteIpAddress");

                b.Property<string>("Token");

                b.Property<int?>("UserEntityId");

                b.Property<int>("UserId");

                b.HasKey("Id");

                b.HasIndex("UserEntityId");

                b.ToTable("RefreshTokens");
            });

            modelBuilder.Entity("Timeify.Core.Entities.UserEntity", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasAnnotation("SqlServer:ValueGenerationStrategy",
                        SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<DateTime>("Created");

                b.Property<string>("FirstName");

                b.Property<string>("IdentityId");

                b.Property<string>("LastName");

                b.Property<DateTime>("Modified");

                b.Property<string>("UserName");

                b.HasKey("Id");

                b.ToTable("Users");
            });

            modelBuilder.Entity("Timeify.Core.Entities.RefreshTokenEntity", b =>
            {
                b.HasOne("Timeify.Core.Entities.UserEntity")
                    .WithMany("RefreshTokens")
                    .HasForeignKey("UserEntityId");
            });
#pragma warning restore 612, 618
        }
    }
}